### PR TITLE
Configure docker and docker-compose

### PR DESCRIPTION
**Pull request by matanzg**
to allow local dev without too much hassle
Update README to help devs get started
Add missing dependency to requirements.txt (bson)

### CODE REVIEW

**Comment by matanzg** [comment]
@ranihorev wouldn't it impact viewing a PDF for the first time? As long as we don't redefine the BUCKET env var, I believe it will create bad links (arxiv.lyrn.ai.s3.amazonaws.com)

**Comment by ranihorev** [comment]
This is the docker PR, we haven't changed the bucket env var here :)
Am I missing something?

**Comment by matanzg** [comment]
Don't we plan to merge the docker pr as well? I was going to release this
rather than keep a long running branch

**Comment by ranihorev** [comment]
Oh, I thought that we'll merge it and run it only in local dev. Do you want to use it in prod as well?
Yes, we need to fix the s3 links (I commented on that on the other PR)

**Comment by matanzg** [comment]
@ranihorev IMO there needs to be a very good reason to maintain a branch outside of master, especially if we intend to onboard developers via docker (which IIUC was the motivation for this request). This branch in particular doesn't impact production, so there's no risk in merging into master.

**Comment by matanzg** [comment]
Oh, sorry - I thought your original comment was for the other branch 🤦 

Yeah, this won't change anything, I'll merge it in now!

**Pull request merged**
